project:
  type: website
  output-dir: .  # Render files directly into the main/root directory
  
website:
  title: "Laura Jochim"
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - text: "Resume"
        href: Resume.pdf
        
        
    right:
      - icon: github
        href: https://github.com/laurajochim
      - icon: orcid
        href: https://orcid.org/0009-0001-4577-4152

format:
  html:
    theme: cosmo   # Use Bootstrap themes like 'cosmo', 'minty', etc.
    css: styles.css

